services:
  go_plugin_compile:
    build:
      context: ./
      dockerfile: Dockerfile.gobuild
      target: golang-base
    command: >
      bash -c "
      go build -o simple.so -buildmode=c-shared .
      && cp ./simple.so /output"
    working_dir: /source
    environment:
    - GOFLAGS=-buildvcs=false
    volumes:
    - .:/source
    - ./lib:/output
